db:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: mattgruter/guacamole-db
  stdin_open: true
guacd:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: mattgruter/guacamole-guacd
  stdin_open: true
Guacamole:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: mattgruter/guacamole-webserver
  links:
  - db:db
  - guacd:server
  stdin_open: true