Plex:
  environment:
    PLEX_USERNAME: "${LOGIN_PLEX}"
    PLEX_PASSWORD: "${PWD_PLEX}"
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: timhaak/plex
  volumes:
  - ${CONFIG_PLEX}:/config
  - ${STORAGE_PLEX}:/data
  stdin_open: true