Transmission:
  environment:
    TRPASSWD: ${PWD_T}
    TRUSER: ${LOGIN_T}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: dperson/transmission
  volumes:
  - ${STORAGE_T}:/var/lib/transmission-daemon/downloads
  stdin_open: true